###
GET http://localhost:3000/api/v1/users

###
GET http://localhost:3000/api/v1/users/3

###
GET http://localhost:3000/api/v1/users/search?q=plot

###
DELETE http://localhost:3000/api/v1/users/1

###
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
    "firstName": "Moshe",
    "lastName": "Plotkin",
    "email": "plotkinm@newpaltz.edu"
}

###
PATCH http://localhost:3000/api/v1/users/31
Content-Type: application/json

{
    "firstName": "Prof. Moshe"
}

// ############################################################################################
// Products

###
GET http://localhost:3000/api/v1/products

###
GET http://localhost:3000/api/v1/products/3

###
GET http://localhost:3000/api/v1/products/search?q=5g 

###
DELETE http://localhost:3000/api/v1/products/1

###
POST http://localhost:3000/api/v1/products
Content-Type: application/json

{
    "title": "Pixel 4",
    "description": "Google's Pixel 4",
    "price": 799.99,
    "thumbnail": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-11-pro-max-silver-select-2019?wid=940&hei=1112&fmt=png-alpha&qlt=80&.v=1566960958082",
    "category": "Electronics",
    "stock": 100

}

###
PATCH http://localhost:3000/api/v1/products/31
Content-Type: application/json

{
    "description": "Google's Pixel 4 with 5G support is the latest flagship phone from Google"
}